---
version: '3'
services:
  nats:
    image: nats
    entrypoint: /nats-server
    command: --name n1 --cluster_name raha --js --sd /data -p 4222
    ports:
      - 4222:4222

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - target: 6831
        published: 6831
        protocol: udp
      - target: 16686
        published: 16686
        protocol: tcp
      - target: 14268
        published: 14268
        protocol: tcp

  emqx:
    image: emqx/emqx
    ports:
      - 1883:1883
      - 18083:18083

  pyroscope:
    image: pyroscope/pyroscope
    ports:
      - 4040:4040
    command:
      - server
