---
name: saf
services:
  saf-consumer:
    build:
      dockerfile: ./build/package/Dockerfile
      context: ..
    environment:
      saf_nats__url: nats://nats:4222
      saf_telemetry__trace__endpoint: jaeger:4317
    command: c

  saf-producer:
    build:
      dockerfile: ./build/package/Dockerfile
      context: ..
    environment:
      saf_nats__url: nats://nats:4222
      saf_telemetry__trace__endpoint: jaeger:4317
    ports:
      - target: 1378
        published: 1378
        protocol: tcp
    command: p

  nats:
    image: docker.io/library/nats
    entrypoint: /nats-server
    command: --name n1 --cluster_name elahe --js --sd /data -p 4222
    ports:
      - 4222:4222

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    ports:
      - target: 4317
        published: 4317
        protocol: tcp
      - target: 16686
        published: 16686
        protocol: tcp
      - target: 14268
        published: 14268
        protocol: tcp

  emqx:
    image: docker.io/emqx/emqx
    ports:
      - 1883:1883
      - 18083:18083
