---
name: saf
services:
  nats:
    image: nats
    entrypoint: /nats-server
    command: --name n1 --cluster_name elahe --js --sd /data -p 4222
    ports:
      - 4222:4222

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - target: 4317
        published: 4317
        protocol: tcp
      - target: 16686
        published: 16686
        protocol: tcp
      - target: 14268
        published: 14268
        protocol: tcp

  emqx:
    image: emqx/emqx
    ports:
      - 1883:1883
      - 18083:18083
