---
version: "2"
linters:
  default: all
  disable:
    - gomodguard
    - wsl
    - depguard
    - tagliatelle
    - nolintlint
    - noinlineerr
    - varnamelen
    - ireturn
    - revive
    - wrapcheck
    - gomoddirectives
    - gosec

  settings:
    wrapcheck:
      ignore-sigs:
        - .JSON
        - .NewHTTPError
        - .Redirect
        - .NoContent
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
