---
version: "3.1"
services:
  nats:
    image: nats
    ports:
      - 4222:4222
  nats-streaming:
    image: nats-streaming
    command:
      - --cluster_id
      - elahe
    ports:
      - 4223:4222
