---
version: "3.1"
services:
  nats:
    image: nats
    hostname: nats
    container_name: nats
    ports:
      - 4222:4222
  nats-streaming:
    image: nats-streaming
    hostname: nats-streaming
    container_name: nats-streaming
    command:
      - --cluster_id
      - nats-ir
    ports:
      - 4223:4222
