---
nats:
  global:
    labels:
      app: jetstream
      team: 1995parham

  natsBox:
    enabled: false

  config:
    merge:
      no_auth_user: legacy
      system_account: admin
      accounts:
        # admin account have access into the system features.
        admin:
          users:
            - user: admin
              password: admin
        legacy:
          users:
            - user: legacy
              # gxywUAjjhnMAqx3ER1CgkX
              password: $2a$11$dIctdLixla7v0eRP/JMA1O./qqcOt87OtXwSrSFQyzwTqf4B03xFy
        # main account's users has their own tenant.
        main:
          jetstream: enabled
          users:
            - user: parham
              # gxywUAjjhnMAqx3ER1CgkX
              password: $2a$11$dIctdLixla7v0eRP/JMA1O./qqcOt87OtXwSrSFQyzwTqf4B03xFy

    cluster:
      noAdvertise: true
      enabled: true
      replicas: 3

    gateway:
      enabled: false

    jetstream:
      enabled: true
      memoryStore:
        enabled: true
        maxSize: 1Gi
      fileStore:
        enabled: true
        storageDirectory: /data
        pvc:
          enabled: true
          size: 2Gi

  container:
    merge:
      resources:
        requests:
          cpu: 1
          memory: 2Gi
          ephemeral-storage: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
          ephemeral-storage: 1Gi

  promExporter:
    enabled: false
    podMonitor:
      enabled: true

