---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saf-producer.fullname" . }}
  labels:
    {{- include "saf-producer.labels" . | nindent 4 }}
data:
  config.yaml: |
    monitoring:
      enabled: true
      address: ":8080"
    {{ with .Values.nats }}
    nats:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    {{ with .Values.logger }}
    logger:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    {{ with .Values.telemetry }}
    telemetry:
      {{ toYaml . | nindent 6 }}
    {{ end }}
