---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saf-producer.fullname" . }}
  labels:
    {{- include "saf-producer.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.envs }}
  saf_{{ $key | lower }}: {{ $value | quote }}
  {{- end }}
