---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saf-consumer.fullname" . }}
  labels:
    {{- include "saf-consumer.labels" . | nindent 4 }}
data:
  config.yaml: |
    monitoring:
      enabled: true
      address: ":8080"
    {{ with .Values.nats }}
    nats:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    {{ with .Values.logger }}
    logger:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    {{ with .Values.telemetry }}
    telemetry:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    {{ with .Values.channels }}
    channels:
      enabled:
      {{ range $name, $configuration := . }}
        - {{ $name }}
      {{ end }}
      configurations:
        {{ toYaml . | nindent 8 }}
    {{ end }}
