---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saf-consumer.fullname" . }}
  labels:
    {{- include "saf-consumer.labels" . | nindent 4 }}
data:
  config.toml: |
    [monitoring]
      enabled = true
      address = ":8080"

    {{- with .Values.nats }}
    {{ toToml ( pick $.Values "nats" ) | nindent 4 }}
    {{- end }}

    {{- with .Values.logger }}
    {{ toToml ( pick $.Values "logger" ) | nindent 4 }}
    {{- end }}

    {{- with .Values.telemetry }}
    {{ toToml ( pick $.Values "telemetry" ) | nindent 4 }}
    {{- end }}

    {{- with .Values.channels }}
    {{ toToml (dict "channels" ( dict "configurations" ( . ) "enabled" ( keys . ) ) ) | nindent 4 }}
    {{- end }}
