apiVersion: v1
kind: Service
metadata:
  name: {{ include "saf-consumer.fullname" . }}
  labels:
    {{- include "saf-consumer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: monitoring
      protocol: TCP
      name: monitoring
  selector:
    {{- include "saf-consumer.selectorLabels" . | nindent 4 }}
