[logger]
level = "info"

[telemetry]

[telemetry.trace]
enabled = true

[telemetry.meter]
address = ":8080"
enabled = true

[channels]
enabled = ["printer", "mqtt"]

[channels.configurations]
printer = {}

[channels.configurations.mqtt]
url = "tcp://127.0.0.1:1883"
