---
logger:
  level: "info"
monitoring:
  address: ":8080"
  enabled: true
telemetry:
  trace:
    enabled: true
  profiler:
    enabled: true
channels:
  enabled:
    - "printer"
    - "mqtt"
  configurations:
    printer: {}
    mqtt:
      url: "tcp://127.0.0.1:1883"
