apiVersion: v1
kind: Service
metadata:
  name: {{ include "saf-producer.fullname" . }}
  labels:
    {{- include "saf-producer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      targetPort: monitoring
      protocol: TCP
      name: monitoring
  selector:
    {{- include "saf-producer.selectorLabels" . | nindent 4 }}
